server:
  port: 5010

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: jonathan
      password: pass
    realmImportFile: blog-realm.json